backend:
  name: github
  repo: jamesjnadeau/addisoncountyfielddays
  branch: master

media_folder: "files/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/files/uploads" # The src attribute for uploaded media will begin with /images/uploads

# publish_mode: editorial_workflow

collections:
  - name: "exhibits"
    label: "Exhibits"
    folder: "content/exhibits"
    create: true
    slug: "{{slug}}"
    format: frontmatter
    extension: md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "date", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      